In [1]:
import pandas as pd
import os
import csv
import glob
import pyet
import math
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error
from scipy import stats
import pickle
from scipy.optimize import curve_fit
import plotly.express as px
import matplotlib.pyplot as plt
#import skill_metrics as sm

In [ ]:
list_of_param = ["ppt", "t_avg", "t_min", "t_max", "ET_fill"]
for param in list_of_param:
    globals()[f"files_with_column_{param}"] = []


def count_columns(directory, parameter, name_param):
    for filename in os.listdir(directory):
        if filename.endswith('.csv'):
            file_path = os.path.join(directory, filename)
            
            try:
                with open(file_path, 'r', newline='') as csvfile:
                    reader = csv.reader(csvfile)
                    headers = next(reader, None)  # Read the header row
                    
                    if headers and f'{name_param}' in headers:
                        parameter.append(filename)
            except Exception as e:
                print(f"Error reading {filename}: {str(e)}")
    # Print the results
    print(f"Files containing f'{name_param}' column:")
    for file in parameter:
        print(file)

    print(f"\nTotal files with f'{name_param}' column: {len(parameter)}")


def analyze_lists(list1, list2, list3, list4):
    # Convert lists to sets for efficient operations
    set1, set2, set3, set4 = map(set, [list1, list2, list3, list4])
    
    # Find common values across all four lists
    common = set1 & set2 & set3 & set4
    
    # Find values unique to each list
    unique1 = set1 - (set2 | set3 | set4)
    unique2 = set2 - (set1 | set3 | set4)
    unique3 = set3 - (set1 | set2 | set4)
    unique4 = set4 - (set1 | set2 | set3)
    
    # Find values in some but not all lists
    not_common = (set1 | set2 | set3 | set4) - common
    
    return {
        "common": common,
        "unique_to_list1": unique1,
        "unique_to_list2": unique2,
        "unique_to_list3": unique3,
        "unique_to_list4": unique4,
        "in_some_but_not_all": not_common
    }
# /mnt/e/flux_ET_dataset/daily_data_files
directory = 'C:\Users\acer\Desktop\final_code\daily_data_files'
count_columns(directory, files_with_column_ppt, "ppt")
count_columns(directory, files_with_column_t_avg, "t_avg")
count_columns(directory, files_with_column_t_min, "t_min")
count_columns(directory, files_with_column_t_max, "t_max")
count_columns(directory, files_with_column_ET_fill, "ET_fill")

common_value = analyze_lists(
    files_with_column_ppt,
    files_with_column_t_avg,
    files_with_column_t_min,
    files_with_column_t_max
)
 
for key, value in common_value.items():
    print(f"{key}: {value}")

with open(f'C:\Users\acer\Desktop\final_code\data\common_value.pkl', 'wb') as f:
    pickle.dump(common_value, f)
# common_value.pkl

Files containing f'ppt' column:
Almond_High_daily_data.csv
Almond_Low_daily_data.csv
Almond_Med_daily_data.csv
BAR012_daily_data.csv
Ellendale_daily_data.csv
JPL1_JV114_daily_data.csv
JPL1_Smith5_daily_data.csv
manilacotton_daily_data.csv
RIP760_daily_data.csv
S2_daily_data.csv
SLM001_daily_data.csv
stonevillesoy_daily_data.csv
US-A32_daily_data.csv
US-A74_daily_data.csv
US-ADR_daily_data.csv
US-AR1_daily_data.csv
US-ARb_daily_data.csv
US-ARc_daily_data.csv
US-ARM_daily_data.csv
US-Aud_daily_data.csv
US-Bi1_daily_data.csv
US-Bi2_daily_data.csv
US-Bkg_daily_data.csv
US-Blk_daily_data.csv
US-Blo_daily_data.csv
US-Bo1_daily_data.csv
US-Br1_daily_data.csv
US-Br3_daily_data.csv
US-Ced_daily_data.csv
US-CMW_daily_data.csv
US-CRT_daily_data.csv
US-Ctn_daily_data.csv
US-Dix_daily_data.csv
US-Dk1_daily_data.csv
US-Dk2_daily_data.csv
US-Esm_daily_data.csv
US-Fmf_daily_data.csv
US-FPe_daily_data.csv
US-FR2_daily_data.csv
US-Fuf_daily_data.csv
US-Fwf_daily_data.csv
US-GLE_daily_data.csv
US-GMF_daily_data.csv
US-Goo_daily_data.csv
US-Hn2_daily_data.csv
US-Hn3_daily_data.csv
US-IB1_daily_data.csv
US-IB2_daily_data.csv
US-Jo2_daily_data.csv
US-KLS_daily_data.csv
US-KS2_daily_data.csv
US-LS1_daily_data.csv
US-Me1_daily_data.csv
US-Me2_daily_data.csv
US-Me5_daily_data.csv
US-Me6_daily_data.csv
US-MMS_daily_data.csv
US-MOz_daily_data.csv
US-NC2_daily_data.csv
US-NC3_daily_data.csv
US-NC4_daily_data.csv
US-Ne1_daily_data.csv
US-Ne2_daily_data.csv
US-Ne3_daily_data.csv
US-NR1_daily_data.csv
US-OF1_daily_data.csv
US-OF2_daily_data.csv
US-OF4_daily_data.csv
US-Oho_daily_data.csv
US-Ro1_daily_data.csv
US-Ro2_daily_data.csv
US-Ro3_daily_data.csv
US-Ro4_daily_data.csv
US-Ro5_daily_data.csv
US-Ro6_daily_data.csv
US-Rwf_daily_data.csv
US-Rws_daily_data.csv
US-SdH_daily_data.csv
US-Skr_daily_data.csv
US-Slt_daily_data.csv
US-Sne_daily_data.csv
US-SO2_daily_data.csv
US-SO3_daily_data.csv
US-SO4_daily_data.csv
US-SP2_daily_data.csv
US-SP3_daily_data.csv
US-SP4_daily_data.csv
US-SRC_daily_data.csv
US-SRG_daily_data.csv
US-SRM_daily_data.csv
US-SRS_daily_data.csv
US-Tw3_daily_data.csv
US-Twt_daily_data.csv
US-Var_daily_data.csv
US-WBW_daily_data.csv
US-WCr_daily_data.csv
US-Wkg_daily_data.csv
US-xAE_daily_data.csv
US-xDC_daily_data.csv
US-xDL_daily_data.csv
US-xDS_daily_data.csv
US-xJR_daily_data.csv
US-xNG_daily_data.csv
US-xNW_daily_data.csv
US-xRM_daily_data.csv
US-xSB_daily_data.csv
US-xSL_daily_data.csv
US-xST_daily_data.csv
US-xUN_daily_data.csv
US-xYE_daily_data.csv

Total files with f'ppt' column: 110
Files containing f't_avg' column:
ALARC2_Smith6_daily_data.csv
Almond_High_daily_data.csv
Almond_Low_daily_data.csv
Almond_Med_daily_data.csv
BAR012_daily_data.csv
Ellendale_daily_data.csv
JPL1_JV114_daily_data.csv
JPL1_Smith5_daily_data.csv
manilacotton_daily_data.csv
MB_Pch_daily_data.csv
RIP760_daily_data.csv
S2_daily_data.csv
SLM001_daily_data.csv
UA1_HartFarm_daily_data.csv
UA1_JV187_daily_data.csv
UA1_KN18_daily_data.csv
UA2_JV330_daily_data.csv
UA2_KN20_daily_data.csv
UA3_JV108_daily_data.csv
UA3_KN15_daily_data.csv
US-A32_daily_data.csv
US-A74_daily_data.csv
US-ADR_daily_data.csv
US-AR1_daily_data.csv
US-ARb_daily_data.csv
US-ARc_daily_data.csv
US-ARM_daily_data.csv
US-Aud_daily_data.csv
US-Bi1_daily_data.csv
US-Bi2_daily_data.csv
US-Bkg_daily_data.csv
US-Blk_daily_data.csv
US-Blo_daily_data.csv
US-Bo1_daily_data.csv
US-Br1_daily_data.csv
US-Br3_daily_data.csv
US-Ced_daily_data.csv
US-CMW_daily_data.csv
US-CRT_daily_data.csv
US-Ctn_daily_data.csv
US-CZ3_daily_data.csv
US-Dix_daily_data.csv
US-Dk1_daily_data.csv
US-Dk2_daily_data.csv
US-Esm_daily_data.csv
US-Fmf_daily_data.csv
US-FPe_daily_data.csv
US-FR2_daily_data.csv
US-Fuf_daily_data.csv
US-Fwf_daily_data.csv
US-GLE_daily_data.csv
US-GMF_daily_data.csv
US-Goo_daily_data.csv
US-Hn2_daily_data.csv
US-Hn3_daily_data.csv
US-IB1_daily_data.csv
US-IB2_daily_data.csv
US-Jo2_daily_data.csv
US-KLS_daily_data.csv
US-KM4_daily_data.csv
US-KS2_daily_data.csv
US-LS1_daily_data.csv
US-MC1_daily_data.csv
US-Me1_daily_data.csv
US-Me2_daily_data.csv
US-Me5_daily_data.csv
US-Me6_daily_data.csv
US-Mj1_daily_data.csv
US-Mj2_daily_data.csv
US-MMS_daily_data.csv
US-MOz_daily_data.csv
US-NC2_daily_data.csv
US-NC3_daily_data.csv
US-NC4_daily_data.csv
US-Ne1_daily_data.csv
US-Ne2_daily_data.csv
US-Ne3_daily_data.csv
US-NR1_daily_data.csv
US-OF1_daily_data.csv
US-OF2_daily_data.csv
US-OF4_daily_data.csv
US-OF6_daily_data.csv
US-Oho_daily_data.csv
US-Ro1_daily_data.csv
US-Ro2_daily_data.csv
US-Ro3_daily_data.csv
US-Ro4_daily_data.csv
US-Ro5_daily_data.csv
US-Ro6_daily_data.csv
US-Rwe_daily_data.csv
US-Rwf_daily_data.csv
US-Rws_daily_data.csv
US-SCg_daily_data.csv
US-SCs_daily_data.csv
US-SCw_daily_data.csv
US-SdH_daily_data.csv
US-Skr_daily_data.csv
US-Slt_daily_data.csv
US-Sne_daily_data.csv
US-SO2_daily_data.csv
US-SO3_daily_data.csv
US-SO4_daily_data.csv
US-SP2_daily_data.csv
US-SP3_daily_data.csv
US-SP4_daily_data.csv
US-SRC_daily_data.csv
US-SRG_daily_data.csv
US-SRM_daily_data.csv
US-Srr_daily_data.csv
US-SRS_daily_data.csv
US-Tw2_daily_data.csv
US-Tw3_daily_data.csv
US-Twt_daily_data.csv
US-Var_daily_data.csv
US-WBW_daily_data.csv
US-WCr_daily_data.csv
US-Wkg_daily_data.csv
US-xAE_daily_data.csv
US-xDC_daily_data.csv
US-xDL_daily_data.csv
US-xDS_daily_data.csv
US-xJR_daily_data.csv
US-xNG_daily_data.csv
US-xNW_daily_data.csv
US-xRM_daily_data.csv
US-xSB_daily_data.csv
US-xSL_daily_data.csv
US-xST_daily_data.csv
US-xUN_daily_data.csv
US-xYE_daily_data.csv

Total files with f't_avg' column: 130
Files containing f't_min' column:
ALARC2_Smith6_daily_data.csv
Almond_High_daily_data.csv
Almond_Low_daily_data.csv
Almond_Med_daily_data.csv
BAR012_daily_data.csv
Ellendale_daily_data.csv
JPL1_JV114_daily_data.csv
JPL1_Smith5_daily_data.csv
manilacotton_daily_data.csv
MB_Pch_daily_data.csv
RIP760_daily_data.csv
S2_daily_data.csv
SLM001_daily_data.csv
UA1_HartFarm_daily_data.csv
UA1_JV187_daily_data.csv
UA1_KN18_daily_data.csv
UA2_JV330_daily_data.csv
UA2_KN20_daily_data.csv
UA3_JV108_daily_data.csv
UA3_KN15_daily_data.csv
US-A32_daily_data.csv
US-A74_daily_data.csv
US-ADR_daily_data.csv
US-AR1_daily_data.csv
US-ARb_daily_data.csv
US-ARc_daily_data.csv
US-ARM_daily_data.csv
US-Aud_daily_data.csv
US-Bi1_daily_data.csv
US-Bi2_daily_data.csv
US-Bkg_daily_data.csv
US-Blk_daily_data.csv
US-Blo_daily_data.csv
US-Bo1_daily_data.csv
US-Br1_daily_data.csv
US-Br3_daily_data.csv
US-Ced_daily_data.csv
US-CMW_daily_data.csv
US-CRT_daily_data.csv
US-Ctn_daily_data.csv
US-CZ3_daily_data.csv
US-Dix_daily_data.csv
US-Dk1_daily_data.csv
US-Dk2_daily_data.csv
US-Esm_daily_data.csv
US-Fmf_daily_data.csv
US-FPe_daily_data.csv
US-FR2_daily_data.csv
US-Fuf_daily_data.csv
US-Fwf_daily_data.csv
US-GLE_daily_data.csv
US-GMF_daily_data.csv
US-Goo_daily_data.csv
US-Hn2_daily_data.csv
US-Hn3_daily_data.csv
US-IB1_daily_data.csv
US-IB2_daily_data.csv
US-Jo2_daily_data.csv
US-KLS_daily_data.csv
US-KM4_daily_data.csv
US-KS2_daily_data.csv
US-LS1_daily_data.csv
US-MC1_daily_data.csv
US-Me1_daily_data.csv
US-Me2_daily_data.csv
US-Me5_daily_data.csv
US-Me6_daily_data.csv
US-Mj1_daily_data.csv
US-Mj2_daily_data.csv
US-MMS_daily_data.csv
US-MOz_daily_data.csv
US-NC2_daily_data.csv
US-NC3_daily_data.csv
US-NC4_daily_data.csv
US-Ne1_daily_data.csv
US-Ne2_daily_data.csv
US-Ne3_daily_data.csv
US-NR1_daily_data.csv
US-OF1_daily_data.csv
US-OF2_daily_data.csv
US-OF4_daily_data.csv
US-OF6_daily_data.csv
US-Oho_daily_data.csv
US-Ro1_daily_data.csv
US-Ro2_daily_data.csv
US-Ro3_daily_data.csv
US-Ro4_daily_data.csv
US-Ro5_daily_data.csv
US-Ro6_daily_data.csv
US-Rwe_daily_data.csv
US-Rwf_daily_data.csv
US-Rws_daily_data.csv
US-SCg_daily_data.csv
US-SCs_daily_data.csv
US-SCw_daily_data.csv
US-SdH_daily_data.csv
US-Skr_daily_data.csv
US-Slt_daily_data.csv
US-Sne_daily_data.csv
US-SO2_daily_data.csv
US-SO3_daily_data.csv
US-SO4_daily_data.csv
US-SP2_daily_data.csv
US-SP3_daily_data.csv
US-SP4_daily_data.csv
US-SRC_daily_data.csv
US-SRG_daily_data.csv
US-SRM_daily_data.csv
US-Srr_daily_data.csv
US-SRS_daily_data.csv
US-Tw2_daily_data.csv
US-Tw3_daily_data.csv
US-Twt_daily_data.csv
US-Var_daily_data.csv
US-WBW_daily_data.csv
US-WCr_daily_data.csv
US-Wkg_daily_data.csv
US-xAE_daily_data.csv
US-xDC_daily_data.csv
US-xDL_daily_data.csv
US-xDS_daily_data.csv
US-xJR_daily_data.csv
US-xNG_daily_data.csv
US-xNW_daily_data.csv
US-xRM_daily_data.csv
US-xSB_daily_data.csv
US-xSL_daily_data.csv
US-xST_daily_data.csv
US-xUN_daily_data.csv
US-xYE_daily_data.csv

Total files with f't_min' column: 130
Files containing f't_max' column:
ALARC2_Smith6_daily_data.csv
Almond_High_daily_data.csv
Almond_Low_daily_data.csv
Almond_Med_daily_data.csv
BAR012_daily_data.csv
Ellendale_daily_data.csv
JPL1_JV114_daily_data.csv
JPL1_Smith5_daily_data.csv
manilacotton_daily_data.csv
MB_Pch_daily_data.csv
RIP760_daily_data.csv
S2_daily_data.csv
SLM001_daily_data.csv
UA1_HartFarm_daily_data.csv
UA1_JV187_daily_data.csv
UA1_KN18_daily_data.csv
UA2_JV330_daily_data.csv
UA2_KN20_daily_data.csv
UA3_JV108_daily_data.csv
UA3_KN15_daily_data.csv
US-A32_daily_data.csv
US-A74_daily_data.csv
US-ADR_daily_data.csv
US-AR1_daily_data.csv
US-ARb_daily_data.csv
US-ARc_daily_data.csv
US-ARM_daily_data.csv
US-Aud_daily_data.csv
US-Bi1_daily_data.csv
US-Bi2_daily_data.csv
US-Bkg_daily_data.csv
US-Blk_daily_data.csv
US-Blo_daily_data.csv
US-Bo1_daily_data.csv
US-Br1_daily_data.csv
US-Br3_daily_data.csv
US-Ced_daily_data.csv
US-CMW_daily_data.csv
US-CRT_daily_data.csv
US-Ctn_daily_data.csv
US-CZ3_daily_data.csv
US-Dix_daily_data.csv
US-Dk1_daily_data.csv
US-Dk2_daily_data.csv
US-Esm_daily_data.csv
US-Fmf_daily_data.csv
US-FPe_daily_data.csv
US-FR2_daily_data.csv
US-Fuf_daily_data.csv
US-Fwf_daily_data.csv
US-GLE_daily_data.csv
US-GMF_daily_data.csv
US-Goo_daily_data.csv
US-Hn2_daily_data.csv
US-Hn3_daily_data.csv
US-IB1_daily_data.csv
US-IB2_daily_data.csv
US-Jo2_daily_data.csv
US-KLS_daily_data.csv
US-KM4_daily_data.csv
US-KS2_daily_data.csv
US-LS1_daily_data.csv
US-MC1_daily_data.csv
US-Me1_daily_data.csv
US-Me2_daily_data.csv
US-Me5_daily_data.csv
US-Me6_daily_data.csv
US-Mj1_daily_data.csv
US-Mj2_daily_data.csv
US-MMS_daily_data.csv
US-MOz_daily_data.csv
US-NC2_daily_data.csv
US-NC3_daily_data.csv
US-NC4_daily_data.csv
US-Ne1_daily_data.csv
US-Ne2_daily_data.csv
US-Ne3_daily_data.csv
US-NR1_daily_data.csv
US-OF1_daily_data.csv
US-OF2_daily_data.csv
US-OF4_daily_data.csv
US-OF6_daily_data.csv
US-Oho_daily_data.csv
US-Ro1_daily_data.csv
US-Ro2_daily_data.csv
US-Ro3_daily_data.csv
US-Ro4_daily_data.csv
US-Ro5_daily_data.csv
US-Ro6_daily_data.csv
US-Rwe_daily_data.csv
US-Rwf_daily_data.csv
US-Rws_daily_data.csv
US-SCg_daily_data.csv
US-SCs_daily_data.csv
US-SCw_daily_data.csv
US-SdH_daily_data.csv
US-Skr_daily_data.csv
US-Slt_daily_data.csv
US-Sne_daily_data.csv
US-SO2_daily_data.csv
US-SO3_daily_data.csv
US-SO4_daily_data.csv
US-SP2_daily_data.csv
US-SP3_daily_data.csv
US-SP4_daily_data.csv
US-SRC_daily_data.csv
US-SRG_daily_data.csv
US-SRM_daily_data.csv
US-Srr_daily_data.csv
US-SRS_daily_data.csv
US-Tw2_daily_data.csv
US-Tw3_daily_data.csv
US-Twt_daily_data.csv
US-Var_daily_data.csv
US-WBW_daily_data.csv
US-WCr_daily_data.csv
US-Wkg_daily_data.csv
US-xAE_daily_data.csv
US-xDC_daily_data.csv
US-xDL_daily_data.csv
US-xDS_daily_data.csv
US-xJR_daily_data.csv
US-xNG_daily_data.csv
US-xNW_daily_data.csv
US-xRM_daily_data.csv
US-xSB_daily_data.csv
US-xSL_daily_data.csv
US-xST_daily_data.csv
US-xUN_daily_data.csv
US-xYE_daily_data.csv

Total files with f't_max' column: 130
Files containing f'ET_fill' column:
AFD_daily_data.csv
AFS_daily_data.csv
ALARC2_Smith6_daily_data.csv
Almond_High_daily_data.csv
Almond_Low_daily_data.csv
Almond_Med_daily_data.csv
BAR012_daily_data.csv
BPHV_daily_data.csv
BPLV_daily_data.csv
B_01_daily_data.csv
B_11_daily_data.csv
DVDV_daily_data.csv
Ellendale_daily_data.csv
ET_1_daily_data.csv
ET_8_daily_data.csv
JPL1_JV114_daily_data.csv
JPL1_Smith5_daily_data.csv
KV_1_daily_data.csv
KV_2_daily_data.csv
KV_4_daily_data.csv
LYS_NE_daily_data.csv
LYS_NW_daily_data.csv
LYS_SE_daily_data.csv
LYS_SW_daily_data.csv
manilacotton_daily_data.csv
MB_Pch_daily_data.csv
MOVAL_daily_data.csv
MR_daily_data.csv
RIP760_daily_data.csv
S2_daily_data.csv
SLM001_daily_data.csv
SPV_1_daily_data.csv
SPV_3_daily_data.csv
stonevillesoy_daily_data.csv
SV_5_daily_data.csv
SV_6_daily_data.csv
TAM_daily_data.csv
UA1_HartFarm_daily_data.csv
UA1_JV187_daily_data.csv
UA1_KN18_daily_data.csv
UA2_JV330_daily_data.csv
UA2_KN20_daily_data.csv
UA3_JV108_daily_data.csv
UA3_KN15_daily_data.csv
UMVW_daily_data.csv
UOVLO_daily_data.csv
UOVMD_daily_data.csv
UOVUP_daily_data.csv
US-A32_daily_data.csv
US-A74_daily_data.csv
US-ADR_daily_data.csv
US-AR1_daily_data.csv
US-ARb_daily_data.csv
US-ARc_daily_data.csv
US-ARM_daily_data.csv
US-Aud_daily_data.csv
US-Bi1_daily_data.csv
US-Bi2_daily_data.csv
US-Bkg_daily_data.csv
US-Blk_daily_data.csv
US-Blo_daily_data.csv
US-Bo1_daily_data.csv
US-Br1_daily_data.csv
US-Br3_daily_data.csv
US-Ced_daily_data.csv
US-CMW_daily_data.csv
US-CRT_daily_data.csv
US-Ctn_daily_data.csv
US-CZ3_daily_data.csv
US-Dix_daily_data.csv
US-Dk1_daily_data.csv
US-Dk2_daily_data.csv
US-Esm_daily_data.csv
US-Fmf_daily_data.csv
US-FPe_daily_data.csv
US-FR2_daily_data.csv
US-Fuf_daily_data.csv
US-Fwf_daily_data.csv
US-GLE_daily_data.csv
US-GMF_daily_data.csv
US-Goo_daily_data.csv
US-Hn2_daily_data.csv
US-Hn3_daily_data.csv
US-IB1_daily_data.csv
US-IB2_daily_data.csv
US-Jo2_daily_data.csv
US-KLS_daily_data.csv
US-KM4_daily_data.csv
US-KS2_daily_data.csv
US-LS1_daily_data.csv
US-MC1_daily_data.csv
US-Me1_daily_data.csv
US-Me2_daily_data.csv
US-Me5_daily_data.csv
US-Me6_daily_data.csv
US-Mj1_daily_data.csv
US-Mj2_daily_data.csv
US-MMS_daily_data.csv
US-MOz_daily_data.csv
US-NC2_daily_data.csv
US-NC3_daily_data.csv
US-NC4_daily_data.csv
US-Ne1_daily_data.csv
US-Ne2_daily_data.csv
US-Ne3_daily_data.csv
US-NR1_daily_data.csv
US-OF1_daily_data.csv
US-OF2_daily_data.csv
US-OF4_daily_data.csv
US-OF6_daily_data.csv
US-Oho_daily_data.csv
US-Ro1_daily_data.csv
US-Ro2_daily_data.csv
US-Ro3_daily_data.csv
US-Ro4_daily_data.csv
US-Ro5_daily_data.csv
US-Ro6_daily_data.csv
US-Rwe_daily_data.csv
US-Rwf_daily_data.csv
US-Rws_daily_data.csv
US-SCg_daily_data.csv
US-SCs_daily_data.csv
US-SCw_daily_data.csv
US-SdH_daily_data.csv
US-Skr_daily_data.csv
US-Slt_daily_data.csv
US-Sne_daily_data.csv
US-SO2_daily_data.csv
US-SO3_daily_data.csv
US-SO4_daily_data.csv
US-SP2_daily_data.csv
US-SP3_daily_data.csv
US-SP4_daily_data.csv
US-SRC_daily_data.csv
US-SRG_daily_data.csv
US-SRM_daily_data.csv
US-Srr_daily_data.csv
US-SRS_daily_data.csv
US-Tw2_daily_data.csv
US-Tw3_daily_data.csv
US-Twt_daily_data.csv
US-Var_daily_data.csv
US-WBW_daily_data.csv
US-WCr_daily_data.csv
US-Wkg_daily_data.csv
US-xAE_daily_data.csv
US-xDC_daily_data.csv
US-xDL_daily_data.csv
US-xDS_daily_data.csv
US-xJR_daily_data.csv
US-xNG_daily_data.csv
US-xNW_daily_data.csv
US-xRM_daily_data.csv
US-xSB_daily_data.csv
US-xSL_daily_data.csv
US-xST_daily_data.csv
US-xUN_daily_data.csv
US-xYE_daily_data.csv
VR_daily_data.csv
WRV_1_daily_data.csv
WRV_2_daily_data.csv

Total files with f'ET_fill' column: 161
common: {'US-xAE_daily_data.csv', 'US-SO3_daily_data.csv', 'US-ARb_daily_data.csv', 'US-NC4_daily_data.csv', 'Almond_Low_daily_data.csv', 'US-SO4_daily_data.csv', 'US-KLS_daily_data.csv', 'US-xNG_daily_data.csv', 'US-Oho_daily_data.csv', 'US-SRM_daily_data.csv', 'US-IB1_daily_data.csv', 'US-Goo_daily_data.csv', 'US-xSB_daily_data.csv', 'US-SdH_daily_data.csv', 'US-SRC_daily_data.csv', 'US-Ro6_daily_data.csv', 'US-ADR_daily_data.csv', 'Ellendale_daily_data.csv', 'US-Ro2_daily_data.csv', 'SLM001_daily_data.csv', 'US-Hn3_daily_data.csv', 'US-xYE_daily_data.csv', 'US-xUN_daily_data.csv', 'US-Me6_daily_data.csv', 'US-Me1_daily_data.csv', 'US-OF2_daily_data.csv', 'US-FR2_daily_data.csv', 'US-NR1_daily_data.csv', 'US-Skr_daily_data.csv', 'manilacotton_daily_data.csv', 'US-Bo1_daily_data.csv', 'US-Ne3_daily_data.csv', 'US-NC2_daily_data.csv', 'US-SO2_daily_data.csv', 'US-xSL_daily_data.csv', 'US-ARc_daily_data.csv', 'US-Hn2_daily_data.csv', 'US-xRM_daily_data.csv', 'US-Fwf_daily_data.csv', 'US-CMW_daily_data.csv', 'US-A32_daily_data.csv', 'US-Ctn_daily_data.csv', 'S2_daily_data.csv', 'BAR012_daily_data.csv', 'US-Jo2_daily_data.csv', 'US-FPe_daily_data.csv', 'Almond_High_daily_data.csv', 'US-Bkg_daily_data.csv', 'US-Blk_daily_data.csv', 'US-Blo_daily_data.csv', 'Almond_Med_daily_data.csv', 'US-IB2_daily_data.csv', 'US-AR1_daily_data.csv', 'US-Dk2_daily_data.csv', 'US-Wkg_daily_data.csv', 'US-Ne2_daily_data.csv', 'US-LS1_daily_data.csv', 'US-Br1_daily_data.csv', 'JPL1_Smith5_daily_data.csv', 'RIP760_daily_data.csv', 'US-GLE_daily_data.csv', 'US-Br3_daily_data.csv', 'US-xNW_daily_data.csv', 'US-Dk1_daily_data.csv', 'US-Ro3_daily_data.csv', 'US-xDL_daily_data.csv', 'US-Ro5_daily_data.csv', 'US-SRG_daily_data.csv', 'US-Slt_daily_data.csv', 'US-Esm_daily_data.csv', 'US-SP2_daily_data.csv', 'US-Var_daily_data.csv', 'US-xJR_daily_data.csv', 'US-xST_daily_data.csv', 'US-Tw3_daily_data.csv', 'US-SP3_daily_data.csv', 'US-Me2_daily_data.csv', 'US-Sne_daily_data.csv', 'JPL1_JV114_daily_data.csv', 'US-OF1_daily_data.csv', 'US-Fmf_daily_data.csv', 'US-KS2_daily_data.csv', 'US-xDS_daily_data.csv', 'US-MMS_daily_data.csv', 'US-WBW_daily_data.csv', 'US-Rws_daily_data.csv', 'US-GMF_daily_data.csv', 'US-Twt_daily_data.csv', 'US-CRT_daily_data.csv', 'US-A74_daily_data.csv', 'US-Fuf_daily_data.csv', 'US-Me5_daily_data.csv', 'US-NC3_daily_data.csv', 'US-WCr_daily_data.csv', 'US-Ro1_daily_data.csv', 'US-SP4_daily_data.csv', 'US-Dix_daily_data.csv', 'US-Ro4_daily_data.csv', 'US-Bi1_daily_data.csv', 'US-Rwf_daily_data.csv', 'US-Bi2_daily_data.csv', 'US-ARM_daily_data.csv', 'US-SRS_daily_data.csv', 'US-xDC_daily_data.csv', 'US-OF4_daily_data.csv', 'US-Aud_daily_data.csv', 'US-Ne1_daily_data.csv', 'US-Ced_daily_data.csv', 'US-MOz_daily_data.csv'}
unique_to_list1: {'stonevillesoy_daily_data.csv'}
unique_to_list2: set()
unique_to_list3: set()
unique_to_list4: set()
in_some_but_not_all: {'US-Tw2_daily_data.csv', 'ALARC2_Smith6_daily_data.csv', 'US-SCw_daily_data.csv', 'UA2_KN20_daily_data.csv', 'US-KM4_daily_data.csv', 'US-CZ3_daily_data.csv', 'US-SCs_daily_data.csv', 'UA3_KN15_daily_data.csv', 'US-Rwe_daily_data.csv', 'UA1_JV187_daily_data.csv', 'US-OF6_daily_data.csv', 'US-SCg_daily_data.csv', 'stonevillesoy_daily_data.csv', 'MB_Pch_daily_data.csv', 'UA1_KN18_daily_data.csv', 'UA1_HartFarm_daily_data.csv', 'US-Mj2_daily_data.csv', 'UA2_JV330_daily_data.csv', 'UA3_JV108_daily_data.csv', 'US-MC1_daily_data.csv', 'US-Mj1_daily_data.csv', 'US-Srr_daily_data.csv'}

In [ ]:
# Specify the directory path and file pattern
# /mnt/e/flux_ET_dataset/daily_data_files/*.csv
file_path = 'C:\Users\acer\Desktop\final_code\daily_data_files\*.csv'
csv_files = glob.glob(file_path)

dfs = []

for file in csv_files:

    ts_data = pd.read_csv(file)

    # Get the file name without extension
    file_name = os.path.splitext(os.path.basename(file))[0]
    # Remove '_daily_data' suffix
    station_name = file_name.replace('_daily_data', '')

    
    ts_data["Site_ID"] = station_name

    dfs.append(ts_data)

merged_df = pd.concat(dfs, ignore_index=True)
merged_df['time'] = pd.to_datetime(merged_df['date'],format= "%Y-%m-%d" )
merged_df

/tmp/ipykernel_955/3055003924.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  merged_df['time'] = pd.to_datetime(merged_df['date'],format= "%Y-%m-%d" )

,date,H,G,Rn,LE,Rn_subday_gaps,H_subday_gaps,LE_subday_gaps,G_subday_gaps,rso,...,theta_40,theta_37,theta_33,theta_35,WD_1_6_1,WD_1_5_1,WS_1_6_1,WS_1_5_1,SW_IN_1_1_3,time
0,2011-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162.406991,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-15
1,2011-11-16,19.330913,-4.123441,19.871779,1.787188,0.0,0.0,0.0,0.0,161.124982,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-16
2,2011-11-17,23.638188,-4.530587,20.304799,1.168036,0.0,0.0,0.0,0.0,159.875084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-17
3,2011-11-18,13.948604,-0.035418,20.660817,0.861524,0.0,0.0,0.0,0.0,158.657738,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-18
4,2011-11-19,15.151694,-7.812638,8.425509,0.416747,0.0,0.0,0.0,0.0,157.473372,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349597,2007-08-27,63.690475,-1.939723,119.097462,NaN,0.0,0.0,13.0,0.0,313.726592,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08-27
349598,2007-08-28,57.191733,-3.528373,104.172713,33.437424,0.0,0.0,0.0,0.0,311.883288,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08-28
349599,2007-08-29,66.305009,0.979109,117.741026,27.717823,0.0,0.0,0.0,0.0,310.019390,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08-29
349600,2007-08-30,51.968193,-2.942493,77.852393,19.561097,0.0,0.0,0.0,0.0,308.135324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08-30
349601,2007-08-31,65.125642,2.422614,121.814802,17.930488,0.0,0.0,0.0,0.0,306.231529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007-08-31

In [4]:
cleaned_names_station = [filename.replace('_daily_data.csv', '') for filename in list(common_value["common"])]
filtered_df = merged_df[merged_df['Site_ID'].isin(cleaned_names_station)]

stations_for_central_valley = ["Almond_High", "Almond_Low", "Almond_Med", "MB_Pch", "RIP760", "SLM001", "US-Bi1", "US-Bi2", "US-Sne", "US-Srr", "US-Tw2", "US-Tw3", "US-Twt"]

filtered_df_for_central_valley = filtered_df[filtered_df['Site_ID'].isin(stations_for_central_valley)]
filtered_df_for_central_valley

,date,H,G,Rn,LE,Rn_subday_gaps,H_subday_gaps,LE_subday_gaps,G_subday_gaps,rso,...,theta_40,theta_37,theta_33,theta_35,WD_1_6_1,WD_1_5_1,WS_1_6_1,WS_1_5_1,SW_IN_1_1_3,time
1586,2016-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.748362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-11
1587,2016-10-12,27.360534,13.438463,110.972908,65.293871,0.0,0.0,0.0,0.0,218.740953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-12
1588,2016-10-13,-4.639130,0.760567,56.696802,54.074164,0.0,0.0,0.0,0.0,216.743060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-13
1589,2016-10-14,11.424929,-5.449675,113.722479,69.963201,0.0,0.0,0.0,0.0,214.755484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-14
1590,2016-10-15,15.930354,-4.330567,99.883296,67.977098,0.0,0.0,0.0,0.0,212.779020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305798,2017-03-31,7.200164,-8.861584,134.162016,156.468848,0.0,0.0,0.0,0.0,277.160037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-03-31
305799,2017-04-01,18.525549,10.674054,147.950895,106.417858,0.0,0.0,0.0,0.0,279.146418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-01
305800,2017-04-02,29.318142,2.353517,141.668119,96.100370,0.0,0.0,0.0,0.0,281.118045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-02
305801,2017-04-03,20.928191,-6.703454,133.792723,111.543462,0.0,0.0,0.0,0.0,283.074323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-03
305802,2017-04-04,27.668749,NaN,NaN,97.864137,0.0,0.0,0.0,0.0,285.014675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-04

In [ ]:
# /mnt/e/flux_ET_dataset/station_metadata_len.csv
dts_data = pd.read_csv("C:\Users\acer\Desktop\final_code\data\station_metadata_len.csv")
df = dts_data[:][:161]

site_location_dict = df.groupby('Site ID').agg({'Latitude': 'first', 'Longitude': 'first'}).apply(tuple, axis=1).to_dict()

# Create a new DataFrame from the dictionary
location_df = pd.DataFrame.from_dict(site_location_dict, orient='index', columns=['lat', 'lon'])
location_df.index.name = 'Site_ID'
location_df.reset_index(inplace=True)

df_merged_final = filtered_df_for_central_valley.merge(location_df, on='Site_ID', how='left')
df_merged_final

,date,H,G,Rn,LE,Rn_subday_gaps,H_subday_gaps,LE_subday_gaps,G_subday_gaps,rso,...,theta_33,theta_35,WD_1_6_1,WD_1_5_1,WS_1_6_1,WS_1_5_1,SW_IN_1_1_3,time,lat,lon
0,2016-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.748362,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-11,36.169669,-120.201004
1,2016-10-12,27.360534,13.438463,110.972908,65.293871,0.0,0.0,0.0,0.0,218.740953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-12,36.169669,-120.201004
2,2016-10-13,-4.639130,0.760567,56.696802,54.074164,0.0,0.0,0.0,0.0,216.743060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-13,36.169669,-120.201004
3,2016-10-14,11.424929,-5.449675,113.722479,69.963201,0.0,0.0,0.0,0.0,214.755484,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-14,36.169669,-120.201004
4,2016-10-15,15.930354,-4.330567,99.883296,67.977098,0.0,0.0,0.0,0.0,212.779020,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-10-15,36.169669,-120.201004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16671,2017-03-31,7.200164,-8.861584,134.162016,156.468848,0.0,0.0,0.0,0.0,277.160037,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-03-31,38.108720,-121.653100
16672,2017-04-01,18.525549,10.674054,147.950895,106.417858,0.0,0.0,0.0,0.0,279.146418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-01,38.108720,-121.653100
16673,2017-04-02,29.318142,2.353517,141.668119,96.100370,0.0,0.0,0.0,0.0,281.118045,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-02,38.108720,-121.653100
16674,2017-04-03,20.928191,-6.703454,133.792723,111.543462,0.0,0.0,0.0,0.0,283.074323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-03,38.108720,-121.653100
16675,2017-04-04,27.668749,NaN,NaN,97.864137,0.0,0.0,0.0,0.0,285.014675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-04-04,38.108720,-121.653100

In [6]:
df_merged_final["latitude_in_radian"] = list(map(math.radians, df_merged_final["lat"]))
df_merged_final.set_index('time', inplace=True)

df_merged_final["eto_hargreaves"] = pyet.hargreaves(
    tmean = df_merged_final["t_avg"],
    tmax = df_merged_final["t_max"],
    tmin = df_merged_final["t_min"],
    lat = df_merged_final["latitude_in_radian"]
)
df_merged_final

,date,H,G,Rn,LE,Rn_subday_gaps,H_subday_gaps,LE_subday_gaps,G_subday_gaps,rso,...,theta_35,WD_1_6_1,WD_1_5_1,WS_1_6_1,WS_1_5_1,SW_IN_1_1_3,lat,lon,latitude_in_radian,eto_hargreaves
time,,,,,,,,,,,,,,,,,,,,,
2016-10-11,2016-10-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.748362,...,NaN,NaN,NaN,NaN,NaN,NaN,36.169669,-120.201004,0.631280,NaN
2016-10-12,2016-10-12,27.360534,13.438463,110.972908,65.293871,0.0,0.0,0.0,0.0,218.740953,...,NaN,NaN,NaN,NaN,NaN,NaN,36.169669,-120.201004,0.631280,3.273054
2016-10-13,2016-10-13,-4.639130,0.760567,56.696802,54.074164,0.0,0.0,0.0,0.0,216.743060,...,NaN,NaN,NaN,NaN,NaN,NaN,36.169669,-120.201004,0.631280,2.934347
2016-10-14,2016-10-14,11.424929,-5.449675,113.722479,69.963201,0.0,0.0,0.0,0.0,214.755484,...,NaN,NaN,NaN,NaN,NaN,NaN,36.169669,-120.201004,0.631280,3.360464
2016-10-15,2016-10-15,15.930354,-4.330567,99.883296,67.977098,0.0,0.0,0.0,0.0,212.779020,...,NaN,NaN,NaN,NaN,NaN,NaN,36.169669,-120.201004,0.631280,2.877207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-03-31,2017-03-31,7.200164,-8.861584,134.162016,156.468848,0.0,0.0,0.0,0.0,277.160037,...,NaN,NaN,NaN,NaN,NaN,NaN,38.108720,-121.653100,0.665123,3.226775
2017-04-01,2017-04-01,18.525549,10.674054,147.950895,106.417858,0.0,0.0,0.0,0.0,279.146418,...,NaN,NaN,NaN,NaN,NaN,NaN,38.108720,-121.653100,0.665123,3.710202
2017-04-02,2017-04-02,29.318142,2.353517,141.668119,96.100370,0.0,0.0,0.0,0.0,281.118045,...,NaN,NaN,NaN,NaN,NaN,NaN,38.108720,-121.653100,0.665123,4.350675
2017-04-03,2017-04-03,20.928191,-6.703454,133.792723,111.543462,0.0,0.0,0.0,0.0,283.074323,...,NaN,NaN,NaN,NaN,NaN,NaN,38.108720,-121.653100,0.665123,3.690431
2017-04-04,2017-04-04,27.668749,NaN,NaN,97.864137,0.0,0.0,0.0,0.0,285.014675,...,NaN,NaN,NaN,NaN,NaN,NaN,38.108720,-121.653100,0.665123,NaN

In [7]:
df_merged_final_filter = df_merged_final.copy()
df_merged_final_filter = df_merged_final_filter[df_merged_final_filter['ET_fill'].apply(lambda x: isinstance(x, float) and not np.isnan(x))]
df_merged_final_filter = df_merged_final_filter[df_merged_final_filter['ppt'].apply(lambda x: isinstance(x, float) and not np.isnan(x))]
df_merged_final_filter = df_merged_final_filter[df_merged_final_filter['eto_hargreaves'].apply(lambda x: isinstance(x, float) and not np.isnan(x))]
# df_merged_final_filter['ET_fill'] = np.where(df_merged_final_filter['ET_fill'] < 0, 0, df_merged_final_filter['ET_fill'])
# df_merged_final_filter['ppt'] = np.where(df_merged_final_filter['ppt'] < 0, 0, df_merged_final_filter['ppt'])
df_merged_final_filter = df_merged_final_filter.query('ET_fill != 0.0')
df_merged_final_filter = df_merged_final_filter.query('ppt != 0.0')

df_filter_parameter = df_merged_final_filter[["date", "ET_fill", "Site_ID", "ppt", "lat", "lon", "latitude_in_radian", "eto_hargreaves"]]

df_filter_parameter['time'] = pd.to_datetime(df_filter_parameter['date'],format= "%Y-%m-%d" )

df_filter_parameter["Month"] = df_filter_parameter["time"].apply(lambda x: x.month)
df_filter_parameter["Year"] = df_filter_parameter["time"].apply(lambda x: x.year)

/tmp/ipykernel_955/1960270433.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter_parameter['time'] = pd.to_datetime(df_filter_parameter['date'],format= "%Y-%m-%d" )
/tmp/ipykernel_955/1960270433.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter_parameter["Month"] = df_filter_parameter["time"].apply(lambda x: x.month)
/tmp/ipykernel_955/1960270433.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter_parameter["Year"] = df_filter_parameter["time"].apply(lambda x: x.year)

In [8]:
monthly_data = df_filter_parameter.groupby(['Site_ID', 'Year', 'Month']).agg({'ET_fill': 'sum',
                                                                              'ppt': 'sum',
                                                                              'eto_hargreaves': 'sum'}).reset_index()

In [9]:
monthly_data_for_basin = monthly_data.groupby(['Year', 'Month']).agg({'ET_fill': 'median',
                                                                      'ppt': 'median',
                                                                      'eto_hargreaves': 'median'}).reset_index()

In [ ]:
terra_climate_delta_s_monthly = pd.read_csv("C:\Users\acer\Desktop\final_code\export\terra_data\data_monthly_basin.csv")
# /mnt/e/flux_ET_dataset/terra_climate/data_monthly_basin.csv
terra_climate_delta_s_yearly = pd.read_csv("C:\Users\acer\Desktop\final_code\export\terra_data\data_basin.csv")
# /mnt/e/flux_ET_dataset/terra_climate/data_basin.csv

In [11]:

yearly_data_for_basin = monthly_data_for_basin.groupby(['Year']).agg({'ET_fill': 'sum',
                                                                      'ppt': 'sum',
                                                                      'eto_hargreaves': 'sum'}).reset_index()

In [12]:
monthly_data_for_basin = monthly_data_for_basin.merge(terra_climate_delta_s_monthly, how="left", on=["Year", "Month"])

yearly_data_for_basin = yearly_data_for_basin.merge(terra_climate_delta_s_yearly, how="left", on=["Year"])

In [13]:
monthly_data_for_basin = monthly_data_for_basin[monthly_data_for_basin['delta'].apply(lambda x: isinstance(x, float) and not np.isnan(x))]
monthly_data_for_basin["pr_delta"] = monthly_data_for_basin["ppt"] - monthly_data_for_basin["delta"]

yearly_data_for_basin = yearly_data_for_basin[yearly_data_for_basin['delta'].apply(lambda x: isinstance(x, float) and not np.isnan(x))]
yearly_data_for_basin["pr_delta"] = yearly_data_for_basin["ppt"] - yearly_data_for_basin["delta"]

In [ ]:
def model_4funcs(Q, w, model):
    if model == "Fu":
        ratio = 1 + Q -(1+(Q)**w)**(1/w)
    if model == "Turc-pike":
        ratio = (1 + Q**(-w))**(-1/w)
    if model == "Zhang":
        ratio = (1 + (w * Q)) * (1 + (w * Q) + (Q**(-1)))**(-1)
    if model == "wang-Tang":
        ratio = (1 + Q - math.sqrt(((1 + Q)**2) - (4 * w * (2 - w)) * Q)) / (2 * w * (2 - w))
    return ratio

In [ ]:
def model_func(x, w):
    return 1 + x - (1 + (x**w))**(1/w)

def aet(ratio, p):
    return ratio * p

In [ ]:
def calculate_metrics(df,name_col):
    df = df.dropna()
    actual = df['ET_fill']
    predicted = df[name_col]

    rmse = np.sqrt(mean_squared_error(actual, predicted))

    nse = 1 - (np.sum((actual - predicted) ** 2) / np.sum((actual - np.mean(actual)) ** 2))

    nrmse = rmse / (np.max(actual) - np.min(actual))

    r = stats.pearsonr(predicted,actual)[0]
    r2= r**2

    mean_value = sum(predicted) / len(predicted)
    var_value = sum(pow(x-mean_value,2) for x in predicted) / len(predicted)  # variance
    std  = math.sqrt(var_value)  # standard deviation

    return rmse, nse, nrmse, r2, r, std

In [16]:
anomalydata = monthly_data_for_basin.groupby(['Month']).agg({'ET_fill': 'mean',
                                                             'ppt': 'mean',
                                                             'eto_hargreaves': 'mean',
                                                             'aet': 'mean',
                                                             'def': 'mean',
                                                             'pr': 'mean',
                                                             'pet': 'mean',
                                                             'ro' : 'mean',
                                                             'delta': 'mean',
                                                             'pr_delta': 'mean'}).reset_index()

In [ ]:
# /mnt/e/Term2/WERI/ML_Budyko/3- result/Budyko_curve/4Models_budyko/result_4models.xlsx
w_result_4model = pd.read_excel("C:\Users\acer\Desktop\final_code\export\terra_data\result_4models.xlsx", sheet_name = "Sheet1")
w_result_4model

        model    scale     W     mae      R2  hs
0          Fu  monthly  9.30  0.2250  0.9133   0
1          Fu  anomaly  4.10  0.1770  0.9330   0
2          Fu   annual  2.22  0.0183  0.5981   0
3   Turc-pike  monthly  8.60  0.0226  0.9132   0
4   Turc-pike  anomaly  3.30  0.0180  0.9328   0
5   Turc-pike   annual  1.46  0.0186  0.6017   0
6       Zhang  monthly  5.00  0.0342  0.7264   0
7       Zhang  anomaly  4.50  0.0139  0.9050   0
8       Zhang   annual  0.39  0.0195  0.6035   0
9   wang-Tang  monthly  0.91  0.0210  0.9139   0
10  wang-Tang  anomaly  0.80  0.0126  0.9330   0
11  wang-Tang   annual  0.45  0.0184  0.5947   0

In [18]:
name_of_models = list(w_result_4model["model"].drop_duplicates())

scale_of_models = list(w_result_4model["scale"].drop_duplicates())
scale_of_models

['monthly', 'anomaly', 'annual']

In [19]:
name_of_models

['Fu', 'Turc-pike', 'Zhang', 'wang-Tang']

In [23]:
# for 4 models "Fu" , "Turc-pike" , "Zhang" , "wang-Tang"
omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]

monthly_data_for_basin[f'ratio_budyko_hargreaves_{name_of_models[3]}'] = monthly_data_for_basin.apply(
    lambda row: model_4funcs(row['eto_hargreaves'] / row['pr_delta'], omega, 'wang-Tang'),
    axis=1
)

monthly_data_for_basin[f'aet_budyko_{name_of_models[3]}'] = monthly_data_for_basin.apply(
    lambda row: aet(row[f'ratio_budyko_hargreaves_{name_of_models[3]}'], row["pr_delta"]),
    axis=1
)

monthly_data_for_basin

/tmp/ipykernel_955/3503651686.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]
/tmp/ipykernel_955/2541960516.py:9: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  ratio = (1 + Q - math.sqrt(((1 + Q)**2) - (4 * w * (2 - w)) * Q)) / (2 * w * (2 - w))

,Year,Month,ET_fill,ppt,eto_hargreaves,aet,def,pr,pet,ro,delta,pr_delta,ratio_budyko_hargreaves_Fu,aet_budyko_Fu,ratio_budyko_hargreaves_Turc-pike,aet_budyko_Turc-pike,ratio_budyko_hargreaves_Zhang,aet_budyko_Zhang,ratio_budyko_hargreaves_wang-Tang,aet_budyko_wang-Tang
0,2009,4,8.290689,22.100,7.429282,19.00,110.30,11.0,131.6,1.0,-5.5,27.600,0.245079,6.764175,0.245016,6.762429,0.229248,6.327255,0.245103,6.764857
1,2009,5,6.472561,17.600,11.523211,12.40,168.65,10.0,186.9,0.0,-3.5,21.100,0.435976,9.199096,0.430879,9.091537,0.398475,8.407825,0.440929,9.303597
2,2009,6,5.417223,9.500,3.296496,7.30,190.80,5.0,201.1,0.0,-2.6,12.100,0.247696,2.997126,0.247598,2.995935,0.231588,2.802209,0.247754,2.997825
4,2009,9,8.310515,1.600,5.217145,4.20,155.10,2.0,159.7,0.0,-1.2,2.800,0.802100,2.245879,0.792971,2.220318,0.762879,2.136061,0.810952,2.270667
5,2009,10,9.522431,4.300,12.645993,37.15,56.30,38.0,95.2,2.0,-1.0,5.300,0.849876,4.504340,0.844021,4.473313,0.821632,4.354647,0.855395,4.533591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,2020,3,17.210329,51.816,20.320406,51.70,34.20,41.0,86.1,2.0,-5.9,57.716,0.308840,17.825036,0.307623,17.754764,0.285928,16.502625,0.309959,17.889578
109,2020,4,8.070300,38.800,11.013723,47.80,90.60,35.0,134.7,2.0,-8.9,47.700,0.213681,10.192604,0.213959,10.205830,0.201079,9.591451,0.213385,10.178483
110,2020,5,3.088043,4.100,5.001569,12.00,182.00,7.0,194.0,0.0,-4.9,9.000,0.441505,3.973547,0.436207,3.925861,0.403404,3.630635,0.446663,4.019964
114,2020,11,1.573960,12.319,4.425902,12.00,43.20,12.0,55.4,1.0,-1.2,13.519,0.290454,3.926652,0.289632,3.915541,0.269638,3.645236,0.291196,3.936672
115,2020,12,3.094037,24.638,8.055164,22.20,12.80,23.0,35.8,1.0,-0.4,25.038,0.286163,7.164942,0.285426,7.146497,0.265831,6.655865,0.286823,7.181476

In [44]:
# for 4 models "Fu" , "Turc-pike" , "Zhang" , "wang-Tang"
omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]

yearly_data_for_basin[f'ratio_budyko_hargreaves_{name_of_models[3]}'] = yearly_data_for_basin.apply(
    lambda row: model_4funcs(row['eto_hargreaves'] / row['pr_delta'], omega, 'wang-Tang'),
    axis=1
)

yearly_data_for_basin[f'aet_budyko_{name_of_models[3]}'] = yearly_data_for_basin.apply(
    lambda row: aet(row[f'ratio_budyko_hargreaves_{name_of_models[3]}'], row["pr_delta"]),
    axis=1
)

yearly_data_for_basin

/tmp/ipykernel_20636/516400155.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]
/tmp/ipykernel_20636/2541960516.py:9: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  ratio = (1 + Q - math.sqrt(((1 + Q)**2) - (4 * w * (2 - w)) * Q)) / (2 * w * (2 - w))

,Year,ET_fill,ppt,eto_hargreaves,aet,def,pr,pet,ro,delta,pr_delta,ratio_budyko_hargreaves_Fu,aet_budyko_Fu,ratio_budyko_hargreaves_Turc-pike,aet_budyko_Turc-pike,ratio_budyko_hargreaves_Zhang,aet_budyko_Zhang,ratio_budyko_hargreaves_wang-Tang,aet_budyko_wang-Tang
0,2009,63.451208,77.0000,74.519949,214.00,1199.70,242.0,1458.55,11.0,10.70,66.3000,0.669794,44.407343,0.657829,43.614081,0.617837,40.962562,0.681872,45.208119
1,2010,129.306847,462.4000,182.474005,338.35,1054.10,399.0,1409.30,20.0,41.60,420.8000,0.365963,153.997356,0.363219,152.842613,0.336417,141.564478,0.368561,155.090515
2,2011,139.680261,229.0000,179.053356,307.95,1088.30,253.0,1389.35,12.0,-65.40,294.4000,0.470517,138.520259,0.464147,136.644857,0.429374,126.407597,0.476776,140.362857
3,2012,116.950344,326.3000,166.538247,252.70,1201.80,322.0,1477.60,17.0,55.65,270.6500,0.474308,128.371464,0.467796,126.609115,0.432782,117.132538,0.480713,130.104997
4,2013,66.517849,94.0350,124.131500,134.60,1327.25,85.0,1488.35,4.0,-58.35,152.3850,0.566938,86.392847,0.557140,84.899763,0.517696,78.889043,0.576792,87.894472
5,2014,65.934823,267.7977,119.559784,189.50,1310.65,267.0,1538.90,13.0,66.50,201.2977,0.462832,93.166970,0.456747,91.942215,0.422475,85.043175,0.468795,94.367423
6,2015,79.960284,167.7460,145.028026,225.60,1244.15,203.0,1503.00,10.0,-28.20,195.9460,0.535184,104.867084,0.526445,103.154813,0.488174,95.655757,0.543919,106.578747
7,2016,91.649611,363.6800,117.765189,317.45,1172.35,336.0,1518.65,18.0,0.10,363.5800,0.287822,104.646427,0.287053,104.366733,0.267303,97.186087,0.288514,104.897773
8,2017,95.062284,355.4120,97.709508,343.35,1163.90,376.5,1522.10,37.0,-20.80,376.2120,0.237436,89.326381,0.237470,89.338961,0.222411,83.673676,0.237370,89.301447
9,2018,91.167748,295.4180,96.681861,268.50,1267.10,277.0,1540.65,13.0,-1.10,296.5180,0.289452,85.827742,0.288650,85.590024,0.268749,79.688920,0.290174,86.041852
10,2019,135.127718,358.4230,138.688627,400.15,1163.20,499.0,1536.25,27.0,31.90,326.5230,0.360001,117.548676,0.357436,116.710962,0.331150,108.127965,0.362424,118.339735
11,2020,49.899795,166.0010,68.004558,200.05,1352.95,141.0,1561.85,8.0,-73.75,239.7510,0.256626,61.526276,0.256399,61.472003,0.239558,57.434205,0.256804,61.569005

In [63]:
# for 4 models "Fu" , "Turc-pike" , "Zhang" , "wang-Tang"
omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]

anomalydata[f'ratio_budyko_hargreaves_{name_of_models[3]}'] = anomalydata.apply(
    lambda row: model_4funcs(row['eto_hargreaves'] / row['pr_delta'], omega, 'wang-Tang'),
    axis=1
)

anomalydata[f'aet_budyko_{name_of_models[3]}'] = anomalydata.apply(
    lambda row: aet(row[f'ratio_budyko_hargreaves_{name_of_models[3]}'], row["pr_delta"]),
    axis=1
)

anomalydata

/tmp/ipykernel_20636/2166048409.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  omega = w_result_4model[w_result_4model["model"] == name_of_models[3]] [w_result_4model["scale"] == scale_of_models[2]]["W"]
/tmp/ipykernel_20636/2541960516.py:9: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  ratio = (1 + Q - math.sqrt(((1 + Q)**2) - (4 * w * (2 - w)) * Q)) / (2 * w * (2 - w))

,Month,ET_fill,ppt,eto_hargreaves,aet,def,pr,pet,ro,delta,pr_delta,ratio_budyko_hargreaves_Fu,aet_budyko_Fu,ratio_budyko_hargreaves_Turc-pike,aet_budyko_Turc-pike,ratio_budyko_hargreaves_Zhang,aet_budyko_Zhang,ratio_budyko_hargreaves_wang-Tang,aet_budyko_wang-Tang
0,1,10.011580,52.041182,18.315534,26.122727,6.781818,46.818182,34.668182,2.272727,16.295455,35.745727,0.416007,14.870480,0.411621,14.713690,0.380718,13.609044,0.420239,15.021758
1,2,16.221135,43.742800,19.765864,35.195000,15.030000,46.800000,51.865000,4.400000,0.800000,42.942800,0.383448,16.466325,0.380157,16.325018,0.351874,15.110445,0.386585,16.601032
2,3,19.304039,57.853091,22.489372,54.563636,32.727273,48.454545,89.418182,2.454545,-7.727273,65.580364,0.302089,19.811100,0.301022,19.741160,0.279950,18.359221,0.303063,19.874976
3,4,10.349336,26.862083,12.878684,45.966667,85.741667,29.416667,132.312500,1.500000,-13.612500,40.474583,0.283479,11.473684,0.282794,11.445966,0.263448,10.662958,0.284090,11.498423
4,5,8.180228,10.796083,10.441598,19.737500,159.004167,11.333333,179.904167,0.416667,-7.933333,18.729417,0.442515,8.288047,0.437180,8.188120,0.404305,7.572390,0.447710,8.385347
5,6,5.269393,6.696400,6.279967,8.550000,197.560000,2.800000,208.940000,0.000000,-5.730000,12.426400,0.411749,5.116558,0.407511,5.063895,0.376939,4.683997,0.415832,5.167293
6,8,6.518943,0.300000,5.418284,2.700000,206.000000,1.000000,210.700000,0.000000,-1.900000,2.200000,0.855214,1.881471,0.849802,1.869564,0.828428,1.822542,0.860296,1.892652
7,9,5.455571,3.655429,5.927170,5.771429,151.578571,3.857143,159.071429,0.000000,-1.814286,5.469714,0.658628,3.602504,0.646763,3.537611,0.606547,3.317637,0.670616,3.668076
8,10,6.254825,16.200333,8.983201,20.416667,81.033333,19.777778,103.033333,1.000000,-1.344444,17.544778,0.415785,7.294847,0.411406,7.218027,0.380520,6.676145,0.420009,7.368960
9,11,10.826872,30.408808,17.075257,29.995833,21.170833,32.833333,53.079167,1.666667,0.479167,29.929642,0.449881,13.464781,0.444276,13.297016,0.410882,12.297548,0.455352,13.628533
10,12,7.439271,38.562667,12.536912,23.658333,8.537500,52.666667,32.866667,2.583333,27.312500,11.250167,0.667188,7.505975,0.655243,7.371592,0.615191,6.920999,0.679249,7.641666

In [ ]:
monthly_data_for_basin['ratio_budyko_hargreaves'] = monthly_data_for_basin.apply(
    lambda row: model_func(row['eto_hargreaves'] / row['pr_delta'], 2.22),
    axis=1
)

monthly_data_for_basin['aet_budyko'] = monthly_data_for_basin.apply(
    lambda row: aet(row['ratio_budyko_hargreaves'], row["pr_delta"]),
    axis=1
)

yearly_data_for_basin['ratio_budyko_hargreaves'] = yearly_data_for_basin.apply(
    lambda row: model_func(row['eto_hargreaves'] / row['pr_delta'], 2.22),
    axis=1
)

yearly_data_for_basin['aet_budyko'] = yearly_data_for_basin.apply(
    lambda row: aet(row['ratio_budyko_hargreaves'], row["pr_delta"]),
    axis=1
)

In [64]:
anomalydata

,Month,ET_fill,ppt,eto_hargreaves,aet,def,pr,pet,ro,delta,pr_delta,ratio_budyko_hargreaves_Fu,aet_budyko_Fu,ratio_budyko_hargreaves_Turc-pike,aet_budyko_Turc-pike,ratio_budyko_hargreaves_Zhang,aet_budyko_Zhang,ratio_budyko_hargreaves_wang-Tang,aet_budyko_wang-Tang
0,1,10.011580,52.041182,18.315534,26.122727,6.781818,46.818182,34.668182,2.272727,16.295455,35.745727,0.416007,14.870480,0.411621,14.713690,0.380718,13.609044,0.420239,15.021758
1,2,16.221135,43.742800,19.765864,35.195000,15.030000,46.800000,51.865000,4.400000,0.800000,42.942800,0.383448,16.466325,0.380157,16.325018,0.351874,15.110445,0.386585,16.601032
2,3,19.304039,57.853091,22.489372,54.563636,32.727273,48.454545,89.418182,2.454545,-7.727273,65.580364,0.302089,19.811100,0.301022,19.741160,0.279950,18.359221,0.303063,19.874976
3,4,10.349336,26.862083,12.878684,45.966667,85.741667,29.416667,132.312500,1.500000,-13.612500,40.474583,0.283479,11.473684,0.282794,11.445966,0.263448,10.662958,0.284090,11.498423
4,5,8.180228,10.796083,10.441598,19.737500,159.004167,11.333333,179.904167,0.416667,-7.933333,18.729417,0.442515,8.288047,0.437180,8.188120,0.404305,7.572390,0.447710,8.385347
5,6,5.269393,6.696400,6.279967,8.550000,197.560000,2.800000,208.940000,0.000000,-5.730000,12.426400,0.411749,5.116558,0.407511,5.063895,0.376939,4.683997,0.415832,5.167293
6,8,6.518943,0.300000,5.418284,2.700000,206.000000,1.000000,210.700000,0.000000,-1.900000,2.200000,0.855214,1.881471,0.849802,1.869564,0.828428,1.822542,0.860296,1.892652
7,9,5.455571,3.655429,5.927170,5.771429,151.578571,3.857143,159.071429,0.000000,-1.814286,5.469714,0.658628,3.602504,0.646763,3.537611,0.606547,3.317637,0.670616,3.668076
8,10,6.254825,16.200333,8.983201,20.416667,81.033333,19.777778,103.033333,1.000000,-1.344444,17.544778,0.415785,7.294847,0.411406,7.218027,0.380520,6.676145,0.420009,7.368960
9,11,10.826872,30.408808,17.075257,29.995833,21.170833,32.833333,53.079167,1.666667,0.479167,29.929642,0.449881,13.464781,0.444276,13.297016,0.410882,12.297548,0.455352,13.628533
10,12,7.439271,38.562667,12.536912,23.658333,8.537500,52.666667,32.866667,2.583333,27.312500,11.250167,0.667188,7.505975,0.655243,7.371592,0.615191,6.920999,0.679249,7.641666

In [68]:
rmse_anomaly, nse_anomaly, nrmse_anomaly, r2_anomaly, r_anomaly, std_anomaly = calculate_metrics(anomalydata, "aet_budyko_wang-Tang")

print(f"RMSE: {rmse_anomaly}")
print(f"NSE: {nse_anomaly}")
print(f"NRMSE: {nrmse_anomaly}")
print(f"R-squared: {r2_anomaly}")
print(f"R: {r_anomaly}")
print(f"standard deviation: {std_anomaly}")

RMSE: 2.348584767183171
NSE: 0.7019003189618336
NRMSE: 0.16734192561598446
R-squared: 0.8359890659760733
R: 0.9143243767810597
standard deviation: 5.443394998565541

In [24]:
monthly_data_for_basin

,Year,Month,ET_fill,ppt,eto_hargreaves,aet,def,pr,pet,ro,delta,pr_delta,ratio_budyko_hargreaves_Fu,aet_budyko_Fu,ratio_budyko_hargreaves_Turc-pike,aet_budyko_Turc-pike,ratio_budyko_hargreaves_Zhang,aet_budyko_Zhang,ratio_budyko_hargreaves_wang-Tang,aet_budyko_wang-Tang
0,2009,4,8.290689,22.100,7.429282,19.00,110.30,11.0,131.6,1.0,-5.5,27.600,0.245079,6.764175,0.245016,6.762429,0.229248,6.327255,0.245103,6.764857
1,2009,5,6.472561,17.600,11.523211,12.40,168.65,10.0,186.9,0.0,-3.5,21.100,0.435976,9.199096,0.430879,9.091537,0.398475,8.407825,0.440929,9.303597
2,2009,6,5.417223,9.500,3.296496,7.30,190.80,5.0,201.1,0.0,-2.6,12.100,0.247696,2.997126,0.247598,2.995935,0.231588,2.802209,0.247754,2.997825
4,2009,9,8.310515,1.600,5.217145,4.20,155.10,2.0,159.7,0.0,-1.2,2.800,0.802100,2.245879,0.792971,2.220318,0.762879,2.136061,0.810952,2.270667
5,2009,10,9.522431,4.300,12.645993,37.15,56.30,38.0,95.2,2.0,-1.0,5.300,0.849876,4.504340,0.844021,4.473313,0.821632,4.354647,0.855395,4.533591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,2020,3,17.210329,51.816,20.320406,51.70,34.20,41.0,86.1,2.0,-5.9,57.716,0.308840,17.825036,0.307623,17.754764,0.285928,16.502625,0.309959,17.889578
109,2020,4,8.070300,38.800,11.013723,47.80,90.60,35.0,134.7,2.0,-8.9,47.700,0.213681,10.192604,0.213959,10.205830,0.201079,9.591451,0.213385,10.178483
110,2020,5,3.088043,4.100,5.001569,12.00,182.00,7.0,194.0,0.0,-4.9,9.000,0.441505,3.973547,0.436207,3.925861,0.403404,3.630635,0.446663,4.019964
114,2020,11,1.573960,12.319,4.425902,12.00,43.20,12.0,55.4,1.0,-1.2,13.519,0.290454,3.926652,0.289632,3.915541,0.269638,3.645236,0.291196,3.936672
115,2020,12,3.094037,24.638,8.055164,22.20,12.80,23.0,35.8,1.0,-0.4,25.038,0.286163,7.164942,0.285426,7.146497,0.265831,6.655865,0.286823,7.181476

In [28]:
rmse_monthly, nse_monthly, nrmse_monthly, r2_monthly, r_monthly, std_monthly = calculate_metrics(monthly_data_for_basin,"aet_budyko_wang-Tang")

print(f"RMSE: {rmse_monthly}")
print(f"NSE: {nse_monthly}")
print(f"NRMSE: {nrmse_monthly}")
print(f"R-squared: {r2_monthly}")
print(f"R: {r_monthly}")
print(f"standard deviation: {std_monthly}")

RMSE: 3.496257687339979
NSE: 0.7512481912527639
NRMSE: 0.11040890613731766
R-squared: 0.7686919628334926
R: 0.8767507985930167
standard deviation: 7.053412635618545

In [ ]:
monthly_data_for_basin.to_csv("C:\Users\acer\Desktop\final_code\export\budyko\result_4models_estimation.csv")
# /mnt/e/Term2/WERI/ML_Budyko/3- result/Budyko_curve/4Models_budyko/result_4models_estimation.csv

In [49]:
rmse_yearly, nse_yearly, nrmse_yearly, r2_yearly, r_yearly, std_yearly = calculate_metrics(yearly_data_for_basin, "aet_budyko_wang-Tang")

print(f"RMSE: {rmse_yearly}")
print(f"NSE: {nse_yearly}")
print(f"NRMSE: {nrmse_yearly}")
print(f"R-squared: {r2_yearly}")
print(f"R: {r_yearly}")
print(f"standard deviation: {std_yearly}")

RMSE: 17.790485893281602
NSE: 0.6270359588935526
NRMSE: 0.1981554192274554
R-squared: 0.7329529393753359
R: 0.8561267075470406
standard deviation: 30.149864612855957